title: Rennan Seimetz Chagas
logo: /assets/img/rennan_chagas_sq.jpg
#description: text below image
birthday: 15 sep 1992
# show_downloads: true
theme: jekyll-theme-minimal

social-network-links:
  email: "chagasrennan@gmail.com"
  # rss: true  # remove this line if you don't want to show an RSS link at the bottom
  linkedin: rseimetz
  github: chagasrennan
  whatsapp: +5521982295186
