title: Rennan Seimetz Chagas
logo: /assets/img/rennan_chagas_sq.jpg
#description: text below image
birthday: 15 September 1992
phone: +55 21 982295186
linkedin: rseimetz
about: I am a 31 years old Brazilian with a PhD in Industrial Engineering & OR. For 12 years I've been responsible for providing optimization and analytics solutions in different fields such as logistics, marketing science, software development, and consulting.
skills:
  programing: Python, VBA, SQL, C++, Git
  modeling: Gurobi, PuLP, Scikit-learn, Scipy
  cloud: Snowflake, BigQuery, AWS, DBT

# show_downloads: true
theme: jekyll-theme-minimal

social-network-links:
  email: "chagasrennan@gmail.com"
  # rss: true  # remove this line if you don't want to show an RSS link at the bottom
  linkedin: rseimetz
  github: chagasrennan
  whatsapp: +5521982295186
